### ISSUE TITLE
async support for Java and Python client library

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/google-cloud-datastore#1]
[b/11970323](http://b/11970323)

using https://github.com/AsyncHttpClient/async-http-client or another popular async http client for Java.
and facilitating integration with python event loop like twisted or tulip.

**Comment by alanw** [comment]
Shameless plug: https://github.com/spotify/async-datastore-client

**Comment by rgruener** [comment]
Any update on this? It seems like now with RPC the java async should be pretty straight forward.

**Comment by rgruener** [comment]
Playing around with this, I added async support in https://github.com/rgruener/google-cloud-datastore/tree/async

Not the cleanest but it works.

**Comment by rgruener** [comment]
Any update on that?

**Comment by tchagnon** [comment]
This is blocking me from using Datastore more widely for high-traffic services.

**Comment by tom12e** [comment]
Any update? I see that the App engine client library supports it.

**Comment by lesv** [comment]
The Spotify Client in comment 2 above is worth checking out.  The preferred API's for Datastore are located at github.com/googlecloudplatform/google-cloud-java  -- Though that doesn't yet support Async either.

**Comment by gruns** [comment]
+1

**Comment by kuldeeprishi** [comment]
+1 for async with pytho

**Comment by meredithslota** [comment]
This repository contains clients that are deliberately low-level and map directly to the underlying Datastore RPC model. Please see these repos instead: https://github.com/googleapis/java-datastore/ and https://github.com/googleapis/python-datastore/
