### ISSUE TITLE
v1beta3 returns Text fields as Strings and doesn't populate Meaning field to distinguish between them

### ISSUE THREAD

**Issue by faizalkassamalisc** [GoogleCloudPlatform/google-cloud-datastore#111]
AppEngine Datastore supports a Text object type:
https://cloud.google.com/appengine/docs/java/datastore/entities#Java_Properties_and_value_types

but Cloud Datastore does not:
https://cloud.google.com/datastore/docs/concepts/entities#properties_and_value_types

As a result, when an Entity with a Text property is inserted from AppEngine, it cannot be properly manipulated from the Cloud Datastore API because com.google.datastore.v1beta3.Value.getMeaning() always returns zero so we can't distinguish a Text object from a String.

Unless I'm missing something, this makes the Cloud Datastore API unusable for those interoperating with the AppEngine Datastore API.

**Comment by pcostell** [comment]
The meaning field for existing values does get set: [Value.meaning](https://github.com/googleapis/googleapis/blob/master/google/datastore/v1beta3/entity.proto#L173). As long as you leave the meaning set as you received it in the v1beta3 API, you should be able to maintain compatibility with your App Engine application.

**Comment by faizalkassamalisc** [comment]
Do you have tests showing the meaning field is populated correctly?  During my testing it always has the value zero.  Happy to share code if helpful.

**Comment by pcostell** [comment]
We do have tests that show it is populated and have built in the preservation of the meaning into many of our clients. Please share a code snippet that populates an entity and then shows the meaning not preserved.

**Comment by faizalkassamalisc** [comment]
Thanks Patrick.  Should I be concerned that gcloud-java just [deprecated the Meaning field](https://github.com/GoogleCloudPlatform/gcloud-java/commit/5b4ea320271b7cdd2734415f5d6578530d551cc1)?

The AppEngine code to set a Text field looks like this:

```
   public void setActiveDays(SortedSet<Date> dates) {
        if (dates != null) {
            String str = Gsons.getInstance().toJson(dates);
            mEntity.setUnindexedProperty("active_days", new Text(str));
        }
    }
```
The AppEngine code to put entity:
`datastore.put(transaction, entityToSave);`


The Cloud API code to get the entity:

```
        LookupRequest.Builder req = LookupRequest.newBuilder();
        req.addKeys(key);
        
        LookupResponse response = datastore.lookup(req.build());

        for (EntityResult entityResult : response.getFoundList()) {
          Entity entity = entityFactory.newAppengineEntity(entityResult.getEntity());
          ...
```

The Cloud API code to parse the returned entity:
```
for (Map.Entry<String, com.google.datastore.v1beta3.Value> propertyEntry : protoEntity.getProperties().entrySet()) {
            com.google.datastore.v1beta3.Value protoBufValue = propertyEntry.getValue();
            Object convertedValue = convertToAppengineValue(propertyEntry.getValue());
            ...

```
The **failing** convertToAppengineValue() code to distinguish between String & Text:
```
if(value.getValueTypeCase() == com.google.datastore.v1beta3.Value.ValueTypeCase.STRING_VALUE {
  System.out.println("\n\nMEANING!!!!! = " + value.getMeaning());
  if (value.getMeaning() == OnestoreEntity.Property.Meaning.TEXT.getNumber()) {
     result = new Text(value.getStringValue());
  } else {
     result = value.getStringValue();
}

```

The relevant output:
```
...
MEANING!!!!! = 0
properties {
      key: "active_days"
      value {
        string_value: "[\"Apr 12, 2016 12:00:00 AM\"]"
        exclude_from_indexes: true
      }
    }
...
```

which matches what I see from the [v1beta3 API explorer](https://developers.google.com/apis-explorer/#p/datastore/v1beta3/datastore.projects.lookup)

```
"active_days": {
      "stringValue": "[\"Apr 12, 2016 12:00:00 AM\"]",
      "excludeFromIndexes": true
     },
```

Shouldn't I see a meaning field?

**Comment by faizalkassamalisc** [comment]
This issue begs the question: why does the list of supported data types in the Cloud Datastore API differ from the AppEngine Datastore API at all?  Doesn't this break (or at least cause pain to) existing AppEngine customers who try to use the Cloud Datastore API to access their data?

![why](http://az616578.vo.msecnd.net/files/2016/03/06/635928653096507481-1615657609_why-god-why1.gif)

**Comment by pcostell** [comment]
Much of this is just trying to make a better API. For example, the fact that Text and an unindexed String are two different types is just silly and a poor API. This happens when an API has been around and backwards compatible for ~8 years. In this case, we are opting for making the API simpler in most cases and only more complicated to maintain backwards compatibility (rather than just making a new version that isn't backwards compatible at all). 

You should see a meaning there, I'll dig into why you can't see it.

**Comment by pcostell** [comment]
Are you sure this specific entity was put as a TextProperty? (and not as a normal String).

Here's what I run (using ndb for the App Engine side):
```
from google.appengine.ext import ndb

class TextKind(ndb.Model):
  value = ndb.TextProperty()

k = TextKind(value="text!").put()
print k
```

Then in the API explorer:
```
POST https://datastore.googleapis.com/v1beta3/projects/<my-project-id>:lookup?key={YOUR_API_KEY}
 
{
 "keys": [
  {
   "path": [
    {
     "kind": "TextKind",
     "id": "5737611108810752"
    }
   ]
  }
 ]
}
```

Response
```
200
 
- Show headers -
  
{
 "found": [
  {
   "entity": {
    "key": {
     "partitionId": {
      "projectId": "<my-project-id>"
     },
     "path": [
      {
       "kind": "TextKind",
       "id": "5737611108810752"
      }
     ]
    },
    "properties": {
     "value": {
      "meaning": 15,
      "stringValue": "text!",
      "excludeFromIndexes": true
     }
    }
   }
  }
 ]
}
```

**Comment by faizalkassamalisc** [comment]
Thanks for your candidness and investigation Patrick.  I'm guessing I had corrupted my datastore entity so the Text became a String.

I created a new test entity and am getting the Meaning field now.  When is the meaning field present?  Should it always be there?
