### ISSUE TITLE
Support gRPC

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/google-cloud-datastore#114]
An enhancement for the datastore emulator to support gRPC. 

> The Datastore Emulator
> gcloud SDK not supported
> 
> As of this release, the Datastore emulator that is part of the gcloud SDK is not compatible with gcloud-node. We use gRPC as our transport layer, while the gcloud SDK's Datastore emulator does not support gRPC.
> Use gcd.sh directly

Or if this is already in the works is their an ETA on this? I would very much like to use the emulator opposed to the gcd-rpc tool because their is no admin console and it would be great to see the items in one place.

**Comment by pcostell** [comment]
This now works with `gcloud` version 116.0.0 (must provide the `--no-legacy` flag to get gRPC).

`gcloud beta emulators datastore start --no-legacy`

Note however that this does not include a viewer for the Datastore.
