### ISSUE TITLE
Return all results with REST API

### ISSUE THREAD

**Issue by danielecook** [GoogleCloudPlatform/google-cloud-datastore#115]
I'm writing an application that uses the REST API. I noticed I can only return 300 results maximum using the GQL interface. Is there a way to increase this? Is there a way to return all results of a query?

**Comment by pcostell** [comment]
Hi --

Right now it is not possible to guarantee that you will get all the results of a query. Eventually we plan to support a gRPC streaming API to return all the entities. Until then, however, we can only return a bounded amount (sometimes it will be less than 300) based on server multitenancy constraints.

Until then, you'll have to use the `more_results` field and the `end_cursor` to implement query batching. Or, you can use one of the `gcloud` client libraries which do the batching for you.
