### ISSUE TITLE
Document datastore production limits

### ISSUE THREAD

**Issue by txomon** [GoogleCloudPlatform/google-cloud-datastore#125]
Hello,

I have found that there is a maximum on the number of entities that can be saved at once and the number of IDs that can be allocated at once.

Please document them!

https://cloud.google.com/datastore/docs/tools/administration

**Comment by pcostell** [comment]
Available at: https://cloud.google.com/datastore/docs/concepts/limits

**Comment by txomon** [comment]
Thanks!
