### ISSUE TITLE
Updating or Deleting a property from an entity by name (Java)

### ISSUE THREAD

**Issue by caioiglesias** [GoogleCloudPlatform/google-cloud-datastore#128]
On Google Cloud Dataflow when adding a property to an entity the process would be

```
Entity oldEntity = c.element();
Entity.Builder entityBuilder = Entity.newBuilder(oldEntity);
entityBuilder.addProperty(
        DatastoreHelper.makeProperty("newProperty",
                DatastoreHelper.makeValue("Value")
        )
);
  c.output(entityBuilder.build());
```

The only foreign elements from the datastore API here are:

- `DatastoreHelper`: returning a property field and a value
- `c`: getting the entity as an input and then outputting another entity.

Shouldn't there be a method to remove, get or set a property by name instead of an int? Adding an existing property produces no error, but saving it to the Datastore service produces an error complaining about a duplicate name for a property.

**Comment by eddavisson** [comment]
In the v1beta3 API, the properties are exposed as an actual map, so this will get a lot simpler once Google Cloud Dataflow is updated to use that API version.

In the meantime, once option is to use `DatastoreHelper.getPropertyMap` to get the properties as a `Map<String, Value>`, modify that map as needed, clear the property list on the `Entity.Builder`, and add back the values from the map.

**Comment by caioiglesias** [comment]
That's what I'm currently doing, but I felt like it could use some improvements. I'll keep following the Dataflow/Beam project as they switch to v1beta3. Thank you very much for the prompt reply @eddavisson .
