### ISSUE TITLE
Bug in the datastore-v1beta3-proto-client lib in the CommitResponse.getMutationResults(0).getKey().getPath(1).getId(); method

### ISSUE THREAD

**Issue by devng** [GoogleCloudPlatform/google-cloud-datastore#129]
In the new API version **v1beta3** when one creates a new entity and provide the parent and child key, thus the child key is not generated by the datastore, then when we commit the request, and try to get the key id object back from the response, the key.path is empty and we get a IndexOutOfBoundsException. Take a look at the example bellow, which is a modified [Guestbook](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/java/demos/src/main/java/com/google/datastore/v1beta3/demos/guestbook/Guestbook.java) code. 

This is a new and strange behavior and it was not the case in **v1beta2** and it is also not the case when the id of the child is auto generated.

``` java
private void addGreeting(String guestbookName, String user, String message) throws DatastoreException {
    Entity.Builder greeting = Entity.newBuilder();

    final Long greetingId = 12345678L;
    final Key.Builder keyBuilder = Key
            .newBuilder()
            .addPath(Key.PathElement.newBuilder().setKind(GUESTBOOK_KIND).setName(guestbookName))
            .addPath(Key.PathElement.newBuilder().setKind(GREETING_KIND).setId(greetingId));

    greeting.setKey(keyBuilder);
    greeting.getMutableProperties().put(USER_PROPERTY, makeValue(user).build());
    greeting.getMutableProperties().put(MESSAGE_PROPERTY, makeValue(message).build());
    greeting.getMutableProperties().put(DATE_PROPERTY, makeValue(new Date()).build());
    Key greetingKey = insert(greeting.build());
    System.out.println("greeting key is: " + greetingKey);
}

private Key insert(Entity entity) throws DatastoreException {
    CommitRequest req = CommitRequest
            .newBuilder()
            .addMutations(Mutation.newBuilder().setInsert(entity))
            .setMode(CommitRequest.Mode.NON_TRANSACTIONAL)
            .build();
    final Key key = datastore.commit(req).getMutationResults(0).getKey();
    final long id = key.getPath(1).getId(); // IndexOutOfBoundsException
    System.out.println("Id = " + id);

    return key;
}
```

This change is not documented anywhere, thus I believe it is a bug. I would really like to have the old v1beta2 behavior back, it would make migration a lot easier.

**Comment by eddavisson** [comment]
In v1beta3, a `MutationResult` only populates the `key` field if the `Key` was automatically allocated (i.e. the last `key.path` element did not populate `name` or `id`). The intent is to save space on the wire. You may want to check out [gcloud-java](https://github.com/GoogleCloudPlatform/gcloud-java) as a higher-level library that hides some of this complexity.

(In v1beta2, the behavior is similar: the `insert_auto_id_key` field in `MutationResult` only contains automatically-allocated `Key`s.)

**Comment by wsh** [comment]
v1beta3 is obsolete (replaced by v1), which should be preferred by users.
