### ISSUE TITLE
Unclear about limits

### ISSUE THREAD

**Issue by Ofekmeister** [GoogleCloudPlatform/google-cloud-datastore#144]
I was reading that there exists a hard limit of 1 update per entity group per second. Say we have Bob & Sally represented as an entity Person with property 'name', among others. If they both update their info at the same time does that mean it will take 2s?

**Comment by eddavisson** [comment]
It's not a hard limit in the sense that if you update an entity group twice in a single second that one of the requests will necessarily fail. But if you are updating an entity group on average more than once per second, it may lead to performance issues.

If the `Person` entities in your example are each in their own entity group:

Bob entity:
```
{
  "key": 
  {
    "path": 
    [
      {
        "kind": "Person",
        "id": "1"
      }
    ]
  },
  "properties": 
  {
    "name": 
    {
      "stringValue": "Bob"
    }
  }
}
```

Sally entity:
```
{
  "key": 
  {
    "path": 
    [
      {
        "kind": "Person",
        "id": "2"
      }
    ]
  },
  "properties": 
  {
    "name": 
    {
      "stringValue": "Sally"
    }
  }
}
```

then you can update each of them once per second.

We'd love to improve the docs on this. Can you let us know where you were reading about the update limit?

**Comment by Ofekmeister** [comment]
@eddavisson Thanks for the quick reply! I was reading [https://cloud.google.com/appengine/docs/python/datastore/entities#Python_Transactions_and_entity_groups](url)

So, if we take user profiles as an example, can we not support many users updating their info at the same time?

**Comment by eddavisson** [comment]
As long as each `Profile` entity has its own entity group (this is the default behavior), then **each** user can update their own profile once per second. Sally can update her profile at the same time Bob updates his without any issue.

**Comment by Ofekmeister** [comment]
So in the example in the docs:

```python
from google.appengine.ext import db

class Employee(db.Model):
  first_name = db.StringProperty()
  last_name = db.StringProperty()
  hire_date = db.DateProperty()
  attended_hr_training = db.BooleanProperty()
```

Each new `employee.put()` would create a new entity group of kind Employee? If so, is an entity the same thing as an entity group?

**Comment by pcostell** [comment]
It depends on how you create your employee. When you create a new `employee = Employee(...)`, if you provide a `parent=db.Key(...)`, then this parent defines the entity group. If you never specify a parent in the constructor, then each entity is in its own entity group.

Where you can run into problems with this method is that queries across entity groups are eventually consistent. [This doc](https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/) goes into detail about it and I highly recommend taking a read through. In your employee example, if each employee is in its own entity group (no `parent=` specified) then any queries across all employees (for example `SELECT * from Employee ORDER BY hire_date`) may not be up-to-date.
