### ISSUE TITLE
Query.setLimit() now takes an Int32Value

### ISSUE THREAD

**Issue by caioiglesias** [GoogleCloudPlatform/google-cloud-datastore#145]
I have started updating my dataflows to use the new API since the betas are getting deprecated in two days and I have a quick question.

Previously on the v1beta* this is how you'd set a limit to a query on DatastoreIO reader:

    import com.google.datastore.v1.Query;
			
	Query.Builder query_builder = Query.newBuilder();
    query_builder.addKindBuilder().setName("Kind");
	query_builder.setLimit(500000);
	Query query = query.build();

Now on V1 setLimit no longer takes an Int as an argument, but an Int32Value object.

Is this how it should go now?

    import com.google.datastore.v1.Query;
    import com.google.protobuf.Int32Value;
			
	Query.Builder query_builder = Query.newBuilder();
    query_builder.addKindBuilder().setName("Kind");
	query_builder.setLimit(Int32Value.newBuilder().setValue(500000).build());
	Query query = query.build();

**Comment by pcostell** [comment]
Yes that works, another option is:

```
query_builder.getLimitBuilder().setValue(500000);
```

The reasoning here is that [proto3](https://developers.google.com/protocol-buffers/) treats an unset primitive and a primitive set to the default value as being equivalent. For `limit`, we need to use the `Int32Value` type to distinguish between a query with no limit and a query with `limit=0`.

**Comment by caioiglesias** [comment]
Thank you Patrick!
