### ISSUE TITLE
Unexpected OK error code with HTTP status code of 401. code=INTERNAL

### ISSUE THREAD

**Issue by janbartel** [GoogleCloudPlatform/google-cloud-datastore#149]
Using gcloud-0.3.0, java environment.

I am deploying a webapp in the appengine flex environment and using gcloud datastore to store http session information.  I receive the error in the title of this issue when I try to execute a projection query (to check if indexes are present) and when I do an Entity query. 

I do **not** receive these errors if I run my webapp locally and talk to gcloud datastore remotely.

I also do **not** receive these errors if I do a gcloud:deploy **after** having run my app locally and inserted an entity into the datastore.

Note that in both cases, the indexes are actually always present. 

![screenshot from 2016-10-05 10-48-51](https://cloud.githubusercontent.com/assets/342406/19097161/1f56be2e-8aee-11e6-8ac6-9ef69c437cd1.png)
![screenshot from 2016-10-05 10-49-47](https://cloud.githubusercontent.com/assets/342406/19097162/1f593de8-8aee-11e6-8cdf-14865e258ffb.png)

I'm attaching screen dumps from the appengine logs to show the problem.

The query to check if indexes are present is:
 Query<ProjectionEntity> query = Query.projectionEntityQueryBuilder()
                    .kind("GCloudSession")
                    .projection("expiry")
                    .filter(PropertyFilter.eq("id", "-"))
                    .build();

The query to check for expired sessions via Entity query is:
Query<Entity> query = Query.entityQueryBuilder()
                .kind("GCloudSession")
                .filter(CompositeFilter.and(PropertyFilter.gt("expiry", 0), PropertyFilter.le("expiry", System.currentTimeMillis())))
                .limit(100)
                .build();

**Comment by janbartel** [comment]
A little more information:

I also get the same "Unexpected OK error ..." when I try to _insert_ an entity into the datastore from my webapp in flex **unless** there is already an entity present (previously inserted by my webapp running locally).

Attaching another screen shot of the log trace.

![screenshot from 2016-10-05 14-15-05](https://cloud.githubusercontent.com/assets/342406/19099939/7aa3550e-8b06-11e6-96fc-a4ef79387467.png)

**Comment by aozarov** [comment]
Were you using Flex Vanilla or Flex Compat?

**Comment by janbartel** [comment]
@aozarov  I was using vm:true.  I also did briefly try env:flex, but there were errors accessing the memcached service so I backed off to just vm:true (which I'm guessing is compat?)

**Comment by aozarov** [comment]
I mean, where you using "runtime: custom" and a non-compat Docker?

**Comment by janbartel** [comment]
app.yaml:
  runtime: custom
  vm: true

docker:
  built off GoogleCloudPlatform/jetty-runtime

**Comment by janbartel** [comment]
@aozarov note that the jetty inside that docker has jetty-gcloud session management enabled, which means that jetty has the gcloud-0.3.0 jars and all their dependencies on its classpath.

**Comment by meltsufin** [comment]
@janbartel do you still have this issue if you use this dependency?
```XML
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>gcloud-java-datastore</artifactId>
      <version>0.2.7</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by janbartel** [comment]
@meltsufin  I cannot reproduce this error today with a freshly deployed app.

Niether can I reproduce it with a previously deployed app that I restarted, and it was failing yesterday!

If I make any headway on this, I'll comment here.

**Comment by EliuX** [comment]
My coworkers starting to use our project are having this issue too. They use Windows by the way. And the 401 error tells this is pretty much a non-authorised error. Is there global variable probably missing for the library to use the Google Cloud Platform as a proxy to the system? It seems they are authenticated inside `gcloud` but the application is doing unauthorised queries.

**Comment by EliuX** [comment]
I solved it by running 
```
gcloud auth application-default login
```
It creates _%HOME%\AppData\Roaming\gcloud\application_default_credentials.json_ which seems the credentials used by the library.
