### ISSUE TITLE
FR: Please point people at GoogleCloudPlatform/google-cloud-java

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/google-cloud-datastore#155]
Unless there is a clear customer advantage, we should be pointing folks at the GA'd libraries.

**Comment by eddavisson** [comment]
Agreed. We do that in the README today:
https://github.com/GoogleCloudPlatform/google-cloud-datastore

and in our docs:
https://cloud.google.com/datastore/docs/reference/libraries

Are there other locations (or messaging) you have in mind?

**Comment by lesv** [comment]
Cool - That's a great start.  I just was cc'd on an issue that reminded me of the repo.  We might wish to consider moving to googlearchive at some point, but probably not for a while.  (Seems quite popular at the moment)

**Comment by ludoch** [comment]
Veneer is GA?

**Comment by lesv** [comment]
My Bad - it's Beta.

**Comment by wsh** [comment]
We do this in the README and in the repo description. I don't think this repo will be going away any time soon, so I'm closing this for now.
