### ISSUE TITLE
Security handshake failed - long queries ( > 2 secs) (nodejs client) 

### ISSUE THREAD

**Issue by VVZen** [GoogleCloudPlatform/google-cloud-datastore#156]
Using the _google-cloud_ package, _node v 6_ and _npm-4.0.5_ on my local macOS machine (10.11.6).
When performing a query to the datastore sometimes the database would spit it out **_Security Handshake failed_** logs (more frequently just after rebooting my express server).
After some seconds (3-4), the query is finally resolved.
The errors all look like this:

`E0106 15:08:31.210244000 123145321271296 handshake.c:128] Security handshake failed: {"created":"@1483711711.210211000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1483711711.210204000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}`

Here's a screenshot (after running a query to check if a user existed) :
![security_handshake_error](https://cloud.githubusercontent.com/assets/10340139/21720687/cd26b8cc-d424-11e6-80ad-33f237bb3395.png)

**Comment by pcostell** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-node#1905
