### ISSUE TITLE
problem with adding dependencies (datastore)

### ISSUE THREAD

**Issue by Cubism** [GoogleCloudPlatform/google-cloud-datastore#159]
when running sbt assembly i am greeted with a series of deduplicate errors. however upon inspecting protobuf-lite nothing is depending on it, but when excluding it in my build.scala file, nothing seems to change.

running sbt assembly snippet:
[error] deduplicate: different file contents found in the following:
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar:com/google/protobuf/GeneratedMessageLite.class
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar:com/google/protobuf/GeneratedMessageLite.class
[error] deduplicate: different file contents found in the following:
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar:com/google/protobuf/UnsafeUtil.class
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar:com/google/protobuf/UnsafeUtil.class
[error] deduplicate: different file contents found in the following:
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar:com/google/protobuf/Utf8$Processor.class
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar:com/google/protobuf/Utf8$Processor.class
[error] deduplicate: different file contents found in the following:
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar:com/google/protobuf/Utf8$SafeProcessor.class
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar:com/google/protobuf/Utf8$SafeProcessor.class
[error] deduplicate: different file contents found in the following:
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar:com/google/protobuf/Utf8$UnsafeProcessor.class
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar:com/google/protobuf/Utf8$UnsafeProcessor.class
[error] deduplicate: different file contents found in the following:
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0/protobuf-java-3.0.0.jar:com/google/protobuf/WireFormat.class
[error] /home/jonathan/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-lite/3.0.1/protobuf-lite-3.0.1.jar:com/google/protobuf/WireFormat.class

build.scala snippet:
  "com.typesafe.slick" %% "slick" % slickVersion,
    "com.typesafe.slick" %% "slick-codegen" % slickVersion,
    "com.typesafe" % "config" % "1.3.0",
    "com.typesafe.slick" %% "slick-hikaricp" % "3.1.1",
    "com.github.tminglei" %% "slick-pg" % "0.11.2",
    "com.twitter" %% "finagle-core" % "6.35.0",
    "com.twitter" %% "finagle-thrift" % "6.35.0",
    "com.twitter" %% "finagle-thriftmux" % "6.35.0",
    "org.postgresql" % "postgresql" % "9.4.1207.jre7",
    "org.apache.thrift" % "libthrift" % "0.9.3",
    "org.scalatest" % "scalatest_2.11" % "2.2.6" % "test",
    "com.fasterxml.jackson.dataformat" % "jackson-dataformat-yaml" % "2.7.3",
    "com.fasterxml.jackson.core" % "jackson-databind" % "2.7.3",
    "com.fasterxml.jackson.core" % "jackson-core" % "2.7.3",
    "com.fasterxml.jackson.core" % "jackson-annotations" % "2.7.3",
    "ch.qos.logback" % "logback-classic" % "1.1.7",
    "com.typesafe.scala-logging" %% "scala-logging" % "3.4.0",
    "net.debasishg" %% "redisclient" % "3.2",
    "com.github.pukkaone" % "logback-gelf" % "1.1.9",
    "org.scala-lang.modules" %% "scala-pickling" % "0.10.1",
    ("com.google.cloud" % "google-cloud-datastore" % "0.8.0-beta").exclude("com.google.protobuf","protobuf-java")

**Comment by mamdouhweb** [comment]
+1

**Comment by wsh** [comment]
Hi there @Cubism! I'm so sorry you've run into this issue, but you're actually not using this library (directly); you're using [google-cloud-java/google-cloud-datastore](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-datastore), which is absolutely the right thing to do. Please update that dep to the latest version (1.14.0; 0.8.0-beta is [more than a year old](https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-datastore)) and try again. If you continue to have issues (fingers crossed!), please file a bug in [google-cloud-java](https://github.com/GoogleCloudPlatform/google-cloud-java) and we'll go from there.
