### ISSUE TITLE
Datastore - TTL like MongoDB (entities expiration)

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-datastore#165]
_From @VVZen on March 15, 2017 15:44_

As a feature request, it would be nice if there was a way to set an **expiration time** for entities.
In this way reset password tokens _(and many other things)_ would be a lot cleaner to implement using Datastore.

Thanks

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2088_

**Comment by stephenplusplus** [comment]
Do you know if this feature in Datastore, and we just don't expose configuration of it? Or would this be a new feature for Datastore? (If so, we'll move it to a better repo for visibility)

**Comment by stephenplusplus** [comment]
_From @VVZen on March 15, 2017 15:48_

I don't know if other clients have this feature, but since I didn't find any mention to it I think they don't.
So maybe it would be better to move it directly to the Datastore repo!

**Comment by sankate** [comment]
These is similar feature request open for some time https://partnerissuetracker.corp.google.com/issues/35902696#

**Comment by thatguystone** [comment]
Here are public links (there seem to be 2 similar issues):

https://issuetracker.google.com/issues/35902696
https://issuetracker.google.com/issues/35877055

**Comment by pataquets** [comment]
Thanks @thatguystone. Starred both issues (thinking of it as voting).
Definitely a +1, more sine Amazon already offering this on Dynamo.

**Comment by danigulyas** [comment]
+1, would be cool! 🕶

**Comment by lcasartelli** [comment]
+1 :D

**Comment by sobacode** [comment]
+1

**Comment by Malinok** [comment]
+1

**Comment by JensRantil** [comment]
A workaround that worked for me was to schedule tasks using `eta=datetime.now() + timedelta(minutes=TTL_MINUTES)` which would then remove the Datastore key.

**Comment by NielsKSchjoedt** [comment]
+1

**Comment by simonsdave** [comment]
+1

**Comment by ruioliveiras** [comment]
+1

**Comment by jcsvwinston** [comment]
+1

**Comment by leighmcculloch** [comment]
+1

**Comment by rplute** [comment]
+1

**Comment by yukiesato** [comment]
+1

**Comment by thanhpk** [comment]
+1

**Comment by djay93** [comment]
+1

**Comment by charlesa101** [comment]
+1

**Comment by Vaibhav** [comment]
+1

**Comment by kmans** [comment]
+1

**Comment by rantonmattei** [comment]
+1

**Comment by LMalikov** [comment]
+1

**Comment by irlaec** [comment]
+1

**Comment by dutradda** [comment]
+1

**Comment by priyakantpatel** [comment]
+1

**Comment by senthilsivanath** [comment]
@elharo Is this implemented ?

**Comment by kaifresh** [comment]
+100000

**Comment by elharo** [comment]
This is the wrong tracker for this request. This repo is just for the client. Entity expiration would have to be implemented in the server.
