### ISSUE TITLE
Slow lookup

### ISSUE THREAD

**Issue by Lisio** [GoogleCloudPlatform/google-cloud-datastore#169]
I have only one lonely entity in datastore and the lookup using it's key is very slow: 0.33-0.42 sec.

This is what curl_getinfo shows (I placed it in GuzzleHttp\Handler\CurlHandler):
```
Array
(
    [url] => https://datastore.googleapis.com/v1/projects/***:lookup
    [content_type] => application/json; charset=UTF-8
    [http_code] => 200
    [header_size] => 393
    [request_size] => 454
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.416758
    [namelookup_time] => 0.060624
    [connect_time] => 0.095299
    [pretransfer_time] => 0.302201
    [size_upload] => 96
    [size_download] => 584
    [speed_download] => 1401
    [speed_upload] => 230
    [download_content_length] => -1
    [upload_content_length] => 96
    [starttransfer_time] => 0.416411
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 64.233.163.95
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 192.168.88.254
    [local_port] => 36792
)
```

Is it really so slow? I tried different server locations to request from and it doesn't have any visible influence on request speed.

Even using compute engine VM instance the speed is extremely slow:
```
Array
(
    [url] => https://datastore.googleapis.com/v1/projects/***:lookup
    [content_type] => application/json; charset=UTF-8
    [http_code] => 200
    [header_size] => 345
    [request_size] => 480
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.457879
    [namelookup_time] => 0.00464
    [connect_time] => 0.009902
    [pretransfer_time] => 0.025045
    [size_upload] => 103
    [size_download] => 591
    [speed_download] => 1290
    [speed_upload] => 224
    [download_content_length] => -1
    [upload_content_length] => 103
    [starttransfer_time] => 0.457698
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 108.177.12.95
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 10.*.*.*
    [local_port] => 46776
)
```

**Comment by thijsterlouw** [comment]
I am seeing the same slowness: from Container Engine (K8s) to Google Cloud Datastore I consistently see simply get operations (by key) taking 400-500ms.

**Comment by Lisio** [comment]
@thijsterlouw Yes, I'm using transient connections but it doesn't matter since I'm measuring response time without pretransfer time. The main problem as I think is that Google uses US IP addresses in DNS for it's API endpoints and when the storage located in Europe region the requests from Russia go to Western Coast of USA, than Google internally requests data from european datacenter and sends response back through US.

It's extremely strange that there are no local endpoints for each region. For instance, europe-west1.datastore.googleapis.com and not just datastore.googleapis.com.

**Comment by thijsterlouw** [comment]
Hi Lisio, that would be extremely inefficient. I was under the impression that GLB (I assume that is used here as well) is smarter: it should resolve to a nearby Google datacenter and from there enter the Google network. Unfortunately I did not see any way to see what my current Cloud Datastore location is (eg if I did not make a mistake and pick US by accident, instead of EU)

**Comment by elharo** [comment]
This seems like an issue with the datastore product rather than the code in this repo specifiically so I'm closing this. If you have a support contract it might help to open a ticket there.
