### ISSUE TITLE
Change datastore-v1-protos to depend on proto-google-common-protos

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-datastore#170]
We encountered the following issue in google-cloud-java: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2020

Basically, all of google-cloud-java pulls in grpc 1.2.0 but datastore-v1-protos pulls in grpc 1.0.1 through the following dependency chain:

`datastore-v1-protos:1.3.0 -> grpc-google-common-protos:0.1.0 -> grpc-all:1.0.1`

We have fixed this by overriding the version in google-cloud-java, but it would be best to fix the source.

Since 0.1.0 of grpc-google-common-protos, we have split generated packages into proto-* for message types and grpc-* for grpc stubs. Thus, the dependency you should use now is `proto-google-common-protos:0.1.9`. Then, we won't have a problem with mismatching grpc versions at all. 

Larger picture: should googleapis take over the generation of datastore-v1-protos? We have fancy batch infrastructure that can keep things up to date.

**Comment by eddavisson** [comment]
It would be awesome for googleapis to take over generating `datastore-v1-protos` (or whatever the standard artifact name would be). We did this already for Python:
https://github.com/GoogleCloudPlatform/google-cloud-datastore/commit/0267a8433e19606c3f2e00c6b333fba42e684818

Is that straightforward from your end? If so, we can skip over fixing the mismatched gRPC versions.

**Comment by garrettjonesgoogle** [comment]
Yeah it's not hard. One impact is that the proto package would no longer be 1.x, because we generate coordinated versions (currently 0.1.9). Also, your `datastore-v1-protos` package would become "orphaned", in that it would no longer see new versions. The artifact would be named `proto-google-cloud-datastore-v1` (same name that Python uses). Would all of this be acceptable?

**Comment by eddavisson** [comment]
Are the packages considered GA? Everything else sounds fine -- we might bump the major version number, but that should be fine.

**Comment by garrettjonesgoogle** [comment]
How disruptive is a major version bump for you?

Our generated packages are not considered GA since they are 0.x.

We could alternatively consider a larger change on our side where we declare proto-google-common-protos and proto-cloud-datastore-v1 GA with a version bump to 1.x. (This results in two coordinated version tracks, one for GA generated packages and one for Beta generated packages). We were basically deferring this until it was going to be necessary somewhere.

**Comment by eddavisson** [comment]
No problem to do a major version bump.

Our preference would be to depend on the GA package, but it would depend a little on what "GA" means. Would the 1.x package just be the same as the 0.1.9 package?

**Comment by garrettjonesgoogle** [comment]
Yes, the packages would be the same either way, the only difference is the version number and the backwards-compatibility guarantee going forward. So, you wouldn't be able to remove or rename methods in the proto without bumping the major version of the generated proto package higher.

**Comment by eddavisson** [comment]
Works for me (since the API is GA, we already can't rename/remove methods).

**Comment by garrettjonesgoogle** [comment]
If we create a GA generated datastore package, would you then retain your current major version when you transition to using it?

**Comment by eddavisson** [comment]
I think we would have to bump it since the protos themselves are part of the public interface of this client.

**Comment by garrettjonesgoogle** [comment]
But the proto-generated classes themselves wouldn't change - they would live in the same location with the same names, and no one would have to change their code. They would just move between artifacts. Does that still count as a breaking change?

**Comment by eddavisson** [comment]
Yes, I think you're right. Okay, then it would just be a minor version update.

**Comment by eddavisson** [comment]
Yes, I think you're right. Okay, then it would just be a minor version update.

**Comment by garrettjonesgoogle** [comment]
We might take a couple months to make this happen, just to be sure we have done the proper GA preparedness for the generated packages.

**Comment by bastova** [comment]
Joining the discussion, since we just encountered the same issue in our project. We are using grpc 1.3.0 which brings in the dependency proto-google-common-protos:1.9.0, which works well for Spanner (relies on 1.9.0) and BigQuery (relies on 1.6.0). However, Datastore relies on the earlier version of common-protos:
`com.google.cloud.datastore#datastore-v1-protos;1.3.0->com.google.api.grpc#grpc-google-common-protos;0.1.0`

These two version seem to be incompatible, specifically around the LocalizedMessage class. We are currently hacking around this issue by modifying the classpath. It would be great to have the datastore dependency updated.

**Comment by paul-hammant** [comment]
Maven shade plugin draws attention to protobuf clash for datastore-v1-proto-client v1.4.0:

```
[WARNING] protobuf-java-3.0.0.jar, protobuf-lite-3.0.1.jar define 144 overlappping classes: 
[WARNING]   - com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder
[WARNING]   - com.google.protobuf.MessageLiteOrBuilder
[WARNING]   - com.google.protobuf.LazyField$LazyEntry
[WARNING]   - com.google.protobuf.AbstractMessageLite
[WARNING]   - com.google.protobuf.UnsafeUtil
[WARNING]   - com.google.protobuf.Utf8
[WARNING]   - com.google.protobuf.LazyStringArrayList$ByteArrayListView
[WARNING]   - com.google.protobuf.GeneratedMessageLite$ExtensionDescriptor
[WARNING]   - com.google.protobuf.SmallSortedMap$EntrySet
[WARNING]   - com.google.protobuf.CodedOutputStream$1
[WARNING]   - 134 more...
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
```

Here is the Dependency tree for datastore-v1-proto-client:1.40

```
+- com.google.cloud.datastore:datastore-v1-proto-client:jar:1.4.0:compile
[INFO] |  +- com.google.cloud.datastore:datastore-v1-protos:jar:1.3.0:compile
[INFO] |  |  +- **com.google.protobuf:protobuf-java:jar:3.0.0**:compile
[INFO] |  |  \- com.google.api.grpc:grpc-google-common-protos:jar:0.1.0:compile
[INFO] |  |     \- io.grpc:grpc-all:jar:1.0.1:compile
[INFO] |  |        +- io.grpc:grpc-auth:jar:1.0.1:compile
[INFO] |  |        |  \- com.google.auth:google-auth-library-credentials:jar:0.4.0:compile
[INFO] |  |        +- io.grpc:grpc-context:jar:1.0.1:compile
[INFO] |  |        +- io.grpc:grpc-protobuf:jar:1.0.1:compile
[INFO] |  |        |  \- com.google.protobuf:protobuf-java-util:jar:3.0.0:compile
[INFO] |  |        +- io.grpc:grpc-netty:jar:1.0.1:compile
[INFO] |  |        |  \- io.netty:netty-codec-http2:jar:4.1.3.Final:compile (version selected from constraint [4.1.3.Final,4.1.3.Final])
[INFO] |  |        +- io.grpc:grpc-stub:jar:1.0.1:compile
[INFO] |  |        +- io.grpc:grpc-protobuf-nano:jar:1.0.1:compile
[INFO] |  |        |  \- com.google.protobuf.nano:protobuf-javanano:jar:3.0.0-alpha-5:compile
[INFO] |  |        +- io.grpc:grpc-core:jar:1.0.1:compile (version selected from constraint [1.0.1,1.0.1])
[INFO] |  |        +- io.grpc:grpc-okhttp:jar:1.0.1:compile
[INFO] |  |        |  +- com.squareup.okio:okio:jar:1.6.0:compile
[INFO] |  |        |  \- com.squareup.okhttp:okhttp:jar:2.5.0:compile
[INFO] |  |        \- io.grpc:grpc-protobuf-lite:jar:1.0.1:compile
[INFO] |  |           \- **com.google.protobuf:protobuf-lite:jar:3.0.1:compile**
[INFO] |  +- com.google.http-client:google-http-client:jar:1.20.0:compile
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.0:compile
[INFO] |  +- com.google.http-client:google-http-client-protobuf:jar:1.20.0:compile
[INFO] |  +- com.google.http-client:google-http-client-jackson:jar:1.20.0:compile
[INFO] |  |  \- org.codehaus.jackson:jackson-core-asl:jar:1.9.11:compile
[INFO] |  +- com.google.oauth-client:google-oauth-client:jar:1.20.0:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.20.0:compile
[INFO] |  |  \- com.google.http-client:google-http-client-jackson2:jar:1.20.0:compile
[INFO] |  \- com.google.guava:guava:jar:21.0:compile
```

**Comment by garrettjonesgoogle** [comment]
Followup: 

* proto-google-common-protos is now GA
* we would like to start generating datastore protos under googleapis to avoid the version conflicts that we are seeing (tracking in https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2621 )

**Comment by eddavisson** [comment]
cc:@wsh 

Sounds good. We should be able to switch over once `proto-google-cloud-datastore-v1` is available in Maven. Do you need anything from us in the mean time? The protos in https://github.com/googleapis/googleapis/tree/master/google/datastore should be up-to-date.

**Comment by garrettjonesgoogle** [comment]
If the protos are up to date then I think we shouldn't need anything else, but I'll let you know if something comes up.

**Comment by wsh** [comment]
Done in 641bd69846bb8347f4dbb0bb263ea78ee9cdc4a8.
