### ISSUE TITLE
Slow query

### ISSUE THREAD

**Issue by Paxa** [GoogleCloudPlatform/google-cloud-datastore#171]
I have 8 records of 1 kind and I select them all. Response time is 500-2000 ms, is it expected?

Code example https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2284

I also tried to use REST HTTP API to get 1 entity by Kind + ID and response time is 500 - 2000 ms

What am I doing wrong?

**Comment by wsh** [comment]
Hey, it seems like your results came from the authentication overhead from the first request (per the discussion on that issue. I'm closing this pre-emptively. If you continue to encounter performance issues and you're sure that they're not related to the environment or Node library, feel free to reopen.
