### ISSUE TITLE
confusing error message

### ISSUE THREAD

**Issue by paul-hammant** [GoogleCloudPlatform/google-cloud-datastore#172]
Guestbook's console output: 

```
Error talking to the datastore: no matching index found. recommended index is:
- kind: greeting
  ancestor: yes
  properties:
  - name: date
    direction: desc
```

I can't work out what I'm supposed to do with that. Sure, I can access the data store online, and start 'create entity' but there's a little correlation with fields in that message above, and controls in the form for 'create entity'.  Why doesn't Guestbook initialize its own schema?

**Comment by wsh** [comment]
Hey there!

1. Datastore is a **schemaless** database, so there's nothing to initialize.
2. What Datastore does require you to do is set up indexes based on the queries you'd like to perform. I'm sorry that wasn't clearer for this demo; take a look [here](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/appengine/guestbook-cloud-datastore/src/main/webapp/WEB-INF/index.yaml) for an example of what you'll need to do.

**Comment by paul-hammant** [comment]
I didn't write Guestbook. I'm commenting on its default output which is hugely confusing to noobs. I was suggesting some more advice for noobs. Not sure why you're explaining about schema-less and closing the issue, versus writing in the README or associated page online - something explaining a more step by step running of the Guestbook demo.
