### ISSUE TITLE
too much contention on these datastore entities. please try again

### ISSUE THREAD

**Issue by JILeXanDR** [GoogleCloudPlatform/google-cloud-datastore#175]
I use Datastore Session Handler and currently I'm getting an error:

```
Datastore upsert failed: {
  "error": {
    "code": 409,
    "message": "too much contention on these datastore entities. please try again.",
    "status": "ABORTED"
  }
}
```

It happens on page where are a few AJAX requests and they write data to the same Entity. How to fix that?

**Comment by wsh** [comment]
Hey there--if I'm understanding you correctly, https://github.com/tomwalder/php-gds-session is what you're using and it's distinct from this code; this is not the right repo for your issue. You can find out more about reducing Datastore contention [here](https://cloud.google.com/appengine/articles/scaling/contention).
