### ISSUE TITLE
How i can connect my laravel app with google cloud datastore and store data ?

### ISSUE THREAD

**Issue by dhamechavivek** [GoogleCloudPlatform/google-cloud-datastore#180]
I can not find any tutorial that give me reference to connect laravel with google cloud datastore and i also want to deploy my laravel on google cloud app engine. so if any anyone have idea please tell me.

**Comment by wsh** [comment]
Hi there! This isn't quite the right repo for your request (this only covers the low-level Python and Java libraries for Datastore, **not** PHP), but have a look at https://github.com/GoogleCloudPlatform/google-cloud-php#google-cloud-datastore-ga and https://github.com/tomwalder/php-gds.
