### ISSUE TITLE
IN operator python

### ISSUE THREAD

**Issue by bcoghe** [GoogleCloudPlatform/google-cloud-datastore#187]
Is it possible to have an 'IN' operation in query.add_filter? It is available in the app engine but not in the standalone api and i don't really get why. Are there plans to do this? Or am i missing something?

**Comment by wsh** [comment]
Hi there @bcoghe,

For Python, ndb offers this support, but the Cloud Datastore API doesn't support it directly at this point. (ndb achieves this by issuing multiple parallel queries). You can follow #36 for updates.

**Comment by bcoghe** [comment]
But you need to run the app engine for this?

Op 26 okt. 2017 11:19 p.m. schreef "Will Hayworth" <notifications@github.com

**Comment by wsh** [comment]
Yes, that's right.

**Comment by bcoghe** [comment]
Well, we are using datastore seperatly and this basis functionality is not
there. I can't imagine it being a lot of trouble for the team to implement
it. As you just said, it's just some parallel queries.. And it is already
in ndb

Op 27 okt. 2017 2:08 a.m. schreef "Will Hayworth" <notifications@github.com
