### ISSUE TITLE
Support IN query filter in node - Array queries for IDs 

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-datastore#189]
_From @mansona on October 10, 2017 10:56_

In the [Java documentation](https://cloud.google.com/appengine/docs/standard/java/datastore/queries) it mentions that you can create a filter using the **IN** operator that is described as follows: 

> IN | Member of (equal to any of the values in a specified list)
> The IN operator also performs multiple queries: one for each item in the specified list, with all other filters unchanged and the IN filter replaced with an EQUAL filter. The results are merged in order of the items in the list. If a query has more than one IN filter, it is performed as multiple queries, one for each possible combination of values in the IN lists.

This raises two questions: Firstly when it says "performs multiple queries" does it mean in the client or on the _other side of the RPC_? I ask so that I can get an idea of the performance profile of this. 

Secondly is there any plan to unify the operators across all client libraries? i.e. will we be getting the **IN** operator in the node client?

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#2662_

**Comment by stephenplusplus** [comment]
cc @pcostell

**Comment by wsh** [comment]
This is not the right repo for this issue. This repo only contains the low-level Java and Python drivers, neither of which offers direct support for the IN operator (which is actually a feature of the Java App Engine Datastore SDK, *not* the Cloud Datastore API); I'll comment on the other issue accordingly.

**Comment by SalathielGenese** [comment]
Hi @wsh ,

I've be struggling with Datastore for awhile now. Please would you link me a link about IN queries ? I'm using NodeJS and want to query array of keys + some DStore ordering but even Python or Java docs/tut/example will help great.

Thank you.
