### ISSUE TITLE
java.lang.NoSuchMethodError: while trying to use datastore

### ISSUE THREAD

**Issue by sachitale** [GoogleCloudPlatform/google-cloud-datastore#196]
I'm using the following dependency:

```
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-datastore</artifactId>
			<version>1.15.0</version>
		</dependency>

```
And I'm running into the following exception:

```
java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:77)
	at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:73)
	at com.google.cloud.RetryHelper.run(RetryHelper.java:73)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:51)
	at com.google.cloud.datastore.DatastoreImpl.beginTransaction(DatastoreImpl.java:436)
	at com.google.cloud.datastore.DatastoreImpl.requestTransactionId(DatastoreImpl.java:430)
	at com.google.cloud.datastore.TransactionImpl.<init>(TransactionImpl.java:59)
	at com.google.cloud.datastore.DatastoreImpl.newTransaction(DatastoreImpl.java:67)
```
This happens because google-cloud-datastore (V 1.15.0) is dependent upon latest guava library, while 
other jars (e.g. google-api-services-calendar [v3-rev285-1.23.0] ) in my project are dependent up on guava-jdk5 jar .

The dependency is transitive:
google-api-services-calendar -> google-api-java-client-release **(V 1.23.0)** -> guava-jdk5

Looks like both these guava jars have same package. So when the code runs in GCP the jdk5 jar seems to being picked up, which in turn doesn't have the new method.

I took a clone from github for google-api-java-client-release-1.23.0 and changed the POM to point to latest guava maven coordinates and it seems to be fixed on my local.

I may be mistaken in picking up the JAR versions. If so please help in choose the right version.

Thanks

**Comment by wsh** [comment]
Hey there @sachitale--first off, I'm sorry you're running into this. Second, what you're encountering is an issue with https://github.com/GoogleCloudPlatform/google-cloud-java, not what this repo provides (the underlying driver that that depends on). Please repost this issue there.

In case it helps: have you thought about excluding the guava-jdk5 dependency [like we do here](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/7dd4c9814cf147bf70badf920adc7226207c748a/java/pom.xml#L73)? That might solve your issue. :smile: If it doesn't, though, let's pick up this discussion in the right repo.
