### ISSUE TITLE
Upgrade Java dependencies to more recent versions

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-datastore#204]

**Comment by paul-hammant** [comment]
Hi Elliotte, maybe for the biiiig break with Guava, the shade plugin could be employed to allow people to move forward elsewhere in their dependency tree.  Ref: https://bryantsai.com/how-to-resolve-dependency-conflict-out-of-your-control-e75ace79e54f :)

**Comment by elharo** [comment]
ATM we're not using shading as a general purpose solution. We're working on some repo-level tooling to try to move dependencies forward more quickly and keep them in sync with each other.

**Comment by paul-hammant** [comment]
Hey Elliotte, here's another project that deliberately shades Guava so that diamond-dependency problems don't happen elsewhere in a larger many-dependency project - https://github.com/paul-hammant/java-driver-shaded-guava. I contributed an upgrade to shade v27.

**Comment by paul-hammant** [comment]
Darn it, that's my fork. Here's the proper repo with PR pending - https://github.com/datastax/java-driver-shaded-guava

**Comment by paul-hammant** [comment]
Between v25.1-jre and v27.0-jre there was a non-backwards-compatible change in a method: 

```
Futures.addCallback(
      final ListenableFuture<V> future,
      final FutureCallback<? super V> callback,
      Executor executor)
```

The last arg, `executor`, is new and backward incompatible.

**Comment by elharo** [comment]
side note: you might have an opinion about this one:

https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/211
On Wed, Aug 1, 2018 at 8:12 AM Paul Hammant <notifications@github.com> wrote:
>
> Hi Elliotte, maybe for the biiiig break with Guava, the shade plugin could be employed to allow people to move forward elsewhere in their dependency tree. Ref: https://bryantsai.com/how-to-resolve-dependency-conflict-out-of-your-control-e75ace79e54f :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Elliotte Rusty Harold
elharo@macfaq.com
