### ISSUE TITLE
consider moving gpg plugin invocation from verify to deploy

### ISSUE THREAD

**Issue by paul-hammant** [GoogleCloudPlatform/google-cloud-datastore#206]
```
@@ -176,7 +176,7 @@
           <executions>
             <execution>
               <id>sign-artifacts</id>
-              <phase>verify</phase>
+              <phase>deploy</phase>
```

^ would help contributors - ppl just wanting send pull-requests :)

**Comment by wsh** [comment]
Hi there! :) This is an interesting idea. It departs from the [maven-gpg-plugin usage guide](https://maven.apache.org/plugins/maven-gpg-plugin/usage.html), though. Could you give us some more context on why we should approve this change?

**Comment by paul-hammant** [comment]
People trying to donate pull-requests to this out of date repo (ref #205)  might like to make a jar so that they can **integration test** it with their solution on their dev workstation.  Unless there is a `--skipGPG=true` build flag that I do not know about they have to do hackery to make the jar because the GPG stage is a hard wall.

**Comment by wsh** [comment]
Why does integration testing require `verify`? (Does `package` not suffice?)
