### ISSUE TITLE
SignedJwtAssertionCredentials used but oauth2client listed > 2.0.0 where it is removed

### ISSUE THREAD

**Issue by thehesiod** [GoogleCloudPlatform/google-cloud-datastore#211]
used here: https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/master/python/googledatastore/helper.py#L98

removed here: https://github.com/google/oauth2client/issues/401

**Comment by elharo** [comment]
Problems seem to go deeper than that. Closing in favor of https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/243 if any more work happens on this at all.
