### ISSUE TITLE
What is the difference between this sdk and the appengine sdk

### ISSUE THREAD

**Issue by mankityau** [GoogleCloudPlatform/google-cloud-datastore#213]
I am sorry, but I don't seems to be able to find the answer anywhere on the internet.

But what is the difference between this sdk and the [com.google.appengine.api.datastore](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/package-summary) sdk.

And which one is recommended to be used?

Best.

**Comment by elharo** [comment]
This is not an SDK at all. You may be asking in the wrong repo.
