### ISSUE TITLE
Optimizing query performance

### ISSUE THREAD

**Issue by cgilboy** [GoogleCloudPlatform/google-cloud-datastore#214]
I am evaluating the speed of datastore and I want to ensure that I am getting the best picture of its performance. 

My test data contains a set of documents, each of which contains a list of logs. Each log has several fields, some of variable size. Each log also has a single indexed field, containing a number.
Something like:
```
{ 
  doc_0: {
    log_0: { field_0_indexed: 124124, field_1: "...", field_2: "...", ...},
    log_1: { field_0_indexed: 42634, field_1: "...", field_2: "...", ...},
    ...
  },
  doc_1: {
    log_0: { field_0_indexed: 34563, field_1: "...", field_2: "...", ...},
    log_1: { field_0_indexed: 8734, field_1: "...", field_2: "...", ...},
    ...
  },
  ...
}
```
I am currently organizing these in datastore by creating entity groups for each document, with the document identifier as the entity group key. All logs are added to their corresponding doc entity group. 

My initial performance test is to query for all logs in a document, like `SELECT * FROM log WHERE __key__ HAS ANCESTOR KEY('doc', 'doc_identifier')`. This takes longer than I expect - about 200ms for documents with 1000-2000 logs. I have tested this through the node.js lib and via curl from a GCE instance. 

Is there another way to organize the data to make these queries execute more quickly? Or is there any other way to make these execute more quickly?

Thanks in advance.

**Comment by elharo** [comment]
This seems to be a question about the datastore product, not this client library in particular. See https://cloud.google.com/datastore/docs/getting-support
