### ISSUE TITLE
Datastore query iteration steps cannot use independent context timeouts

### ISSUE THREAD

**Issue by daboyuka** [GoogleCloudPlatform/google-cloud-datastore#245]
When iterating over datastore query results, a context with deadline may be used to limit the time allowed for the entire query. However, individual calls to Iterator.Next cannot currently be configured with independent, shorter deadlines, since they all share a single context deadline.

Practically, this means that a large query must either A) use a long deadline, leading to slow reaction time of calling code in response to contention, etc., or B) use a short deadline, leading to many spurious restarts of the query.

Instead, allowing independent contexts, or perhaps better, independent sub-deadlines/timeouts for each call to Iterator.Next / .nextBatch, would improve visibility of datastore contention to calling code.

Snippets from current code in `cloud.google.com/go/datastore`:
```
func (c *Client) Run(ctx context.Context, q *Query) *Iterator {
	...
	t := &Iterator{
		ctx: ctx, ...
	}
	...
}

func (t *Iterator) nextBatch() error {
	...
	resp, err := t.client.client.RunQuery(t.ctx, t.req)
	...
}
```

*Expected behavior*: the ability to either pass a `context.Context` to `datastore.Iterator.Next`, or perhaps to pass a per-step timeout during construction of the query or iterator, such that internally the context passed to the inner client would be wrapped in (another) layer of `context.WithTimeout` using that smaller timeout.

Note: this is a *regression* in practice vs. the legacy AppEngine Datastore library, which appears to use a short (5-second?) timeout on each underlying AppEngine API call during iterator Next.

**Comment by tbpg** [comment]
Thank you for filing this! The Go Datastore client is in a different repo, so I copied this issue over there: https://github.com/googleapis/google-cloud-go/issues/1663.
