### ISSUE TITLE
Add OpenCensus tracing/stats support

### ISSUE THREAD

**Issue by alysyk** [GoogleCloudPlatform/google-cloud-datastore#248]
We're in the process of moving for AppEngine Standard to Flex, thus we're now using the Google Cloud Datastore APIs. Unfortunately, these APIs are not using OpenCensus Tracing and Stats to transmit relevant data.

Please consider this as a feature request for parity.

**Comment by BenWhitehead** [comment]
Closing in favor of https://github.com/googleapis/java-datastore/issues/109
