### ISSUE TITLE
Reasons for using in Datastore mode instead of Native mode through Firestore

### ISSUE THREAD

**Issue by manwithsteelnerves** [GoogleCloudPlatform/google-cloud-datastore#251]
We are planning to use Firestore for a product where we want to use the database to serve our REST API.
We don't be using any mobile sdk's firestore offers so are there any benefits of using Firestore in datastore mode instead of native mode?

One benefit I see is related to no write limits so wondering if datastore mode is the one to go.

**Comment by manwithsteelnerves** [comment]
Thanks Ben for the link. Unfortunately, the document is too biased towards Firestore in native mode so would like to know your opinion on this.

Considering the use-case is only server side only (and no mobile sdk usage), Datastore mode is more beneficial  when it comes to cost and overhead right?

**Comment by BenWhitehead** [comment]
If you don't plan on needing to use any of the mobile features, and you don't plan on needing to use any of the document events (Query Watch, Cloud Function trigger) then Datastore Mode should be able to work very well for you.

**Comment by manwithsteelnerves** [comment]
We don't need any of the mobile features. I see Datastore mode is more related for my use-case but unfortunately I noticed it doesn't have triggers. 

Do you see any alternatives/workarounds w.r.t triggers for Datastore mode?

**Comment by BenWhitehead** [comment]
I think you could look into doing something with Pub/Sub along with Datastore. When your app performs a write to datastore it could also write an event to pubsub. Past this simple example we don't have any sort of reference implementation that we can recommend.

**Comment by manwithsteelnerves** [comment]
Thanks Ben for sharing. I will contact gcp support on the same.
