### ISSUE TITLE
Intermittent delay for being able to get an entity by query

### ISSUE THREAD

**Issue by LondonAppDev** [GoogleCloudPlatform/google-cloud-datastore#252]
I am building an application and using the Cloud Datastore Emulator (2.1.0) and the `google-cloud-ndb` Python library (1.6) to develop locally.

When using the datastore beta emulator, there seems to be an intermittent delay for being able to retrieve an entity by query.

For example, take this code:

```python
my_entity = MyEntity(foo='bar')
my_entity.put()

get_my_entity = MyEntity.query().filter(MyEntity.foo == 'bar').get()
print(get_my_entity.foo)
```

If I run this, it will fail intermittently (approx. 1/10 times) because the `get()` method returns `None`.

In-case anyone wants to re-produce the issue locally, I've created a full script along with a docker-compose configuration here: [https://github.com/LondonAppDev/cloud-datastore-example](https://github.com/LondonAppDev/cloud-datastore-example) (the script is in [datastore.py](https://github.com/LondonAppDev/cloud-datastore-example/blob/main/datastore.py)).

I posted [this question](https://stackoverflow.com/questions/64047498/datastore-delay-on-creating-entities-with-put) on StackOverflow, and someone suggested trying to get the entity using `get_by_id()`. I tried this and it worked reliably, which suggests the issue may be with indexing?

Additionally, I tested the above code on a GAE + Datastore project and it also worked reliably.

To me, this suggests there is a bug with the datastore emulator itself. Unless it's expected that there will always be a (potential) delay on indexing when using the local datastore emulator?

Thanks in advance for any suggestions or comments on anything I may be doing incorrectly.

**Comment by pcostell** [comment]
Looking at your repo, it looks like you just found the `--consistency` flag. Can you confirm that fixes the issue you are seeing?

**Comment by LondonAppDev** [comment]
@pcostell thanks a lot for the response. Yes I did find the `--consistency` flag and unforutnately setting `--consistency=1.0` does not fix the problem.

**Comment by pcostell** [comment]
To double check, did you rebuild your container? Grabbing a fresh copy and running (per your reproduction instructions) I seem to get a success every time (out of 3 attempts).

**Comment by LondonAppDev** [comment]
@pcostell 🤦 you're right, it does work with `--consistency=1.0`. 

I had re-built the container but I think it didn't update due to the docker cache. After building with `--no-cache` and deleting the `data/` directory created by the emulator, it is working with `--consitency=1.0`.

Thanks so much for checking and apologies for taking up your time unecessarily.
