### ISSUE TITLE
Better error message for Backend Error

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/google-cloud-datastore#27]
[b/11969636](http://b/11969636)

Currently some non transactional write can failed with:
```
Backend Error
```

We should provide a more comprehensive error about what happens, and hint the user that he should retry the operation.

**Comment by eddavisson** [comment]
API error messages are generally more informative in the v1beta3 API. In particular, query results are returned in smaller batches, so the API will not return "Backend Error" this scenario.
