### ISSUE TITLE
Add support for App Engine Java client library

### ISSUE THREAD

**Issue by proppy** [GoogleCloudPlatform/google-cloud-datastore#34]
Add support for App Engine Java client library (as well as objectify), as requested on http://stackoverflow.com/questions/21502396/communication-with-datastore-and-cloud-storage-from-google-compute-engine-in-jav

**Comment by fawzyj** [comment]
Any updated on this ticket? we need an easy api to use Cloud datastore !

**Comment by faizalkassamalisc** [comment]
![bueller](https://media.giphy.com/media/sW6P26sp3HFvy/giphy.gif)

**Comment by pcostell** [comment]
Using the App Engine API will be supported with the next version of the Cloud Datastore API. If you'd like an easy to use Cloud Datastore API, I'd suggest taking a look at https://github.com/GoogleCloudPlatform/gcloud-java

**Comment by faizalkassamalisc** [comment]
Thanks @pcostell.  That's great to hear!  Are you able to share a little more detail?  When is the next version of the Cloud Datastore API expected to release?  What will the version number be?  Is preliminary support already checked in to the repo?

**Comment by pcostell** [comment]
The next version of the API (v1beta3) should be released this quarter (see #5 for some more details). This version will look very similar to the v1beta2 API (we'll have release notes detailing the differences).

There is preliminary support for this already built into the App Engine APIs for Java and python but the requests to the new API would fail if you tried to use it. This repo doesn't have any code with support for the new version, but we have a private fork which will get merged in once the new API is released. Many of the gcloud libraries also have support in non-master forks for the new version that will be merged into their master branches once the new API is accessible.

**Comment by faizalkassamalisc** [comment]
Thanks @pcostell.  I was bemused to learn of yet another google-provided API for accessing Datastore but I did check out [gcloud-java](https://github.com/GoogleCloudPlatform/gcloud-java) as you suggested.  Seems promising at first but it doesn't appear to have feature parity.  For example, the gcloud-java [Datastore interface](http://googlecloudplatform.github.io/gcloud-java/0.1.3/apidocs/com/google/gcloud/datastore/Datastore.html) does not implement methods such as getCurrentTransactions and prepare(Query) provided by appengine's [BaseDatastoreService interface](https://cloud.google.com/appengine/docs/java/javadoc/com/google/appengine/api/datastore/BaseDatastoreService).  Let me know if I'm missing something here.

**Comment by pcostell** [comment]
It is missing the `getCurrentTransactions` method, but it does support `prepare` via the `run` method. The key class also has a `kind()` method.

If there are things missing there that have a good use case, I'd suggest filing a FR on the gcloud-java page.

**Comment by aozarov** [comment]
Hey @faizalkassamalisc. Yes, as @pcostell said `Key` does have a kind and expose it via the [kind()](http://googlecloudplatform.github.io/gcloud-java/0.1.3/apidocs/com/google/gcloud/datastore/BaseKey.html#kind()) accessor. In gcloud-java we prefer not to follow the JavaBean style conventions for accessors.

We do follow a different API pattern for handling transactions and didn't see a need for a client-side `getCurrentTransaction` or `getActiveTransactions` bookkeeping. Please let us [know](https://github.com/GoogleCloudPlatform/gcloud-java/issues) if you see a useful use-case that demonstrate otherwise or have any other issues or suggestions.

**Comment by faizalkassamalisc** [comment]
Thanks @aozarov.  I think that should be fine for our use case.

Is v1beta3 still on track to "be released this quarter" as per @pcostell's earlier comment?

**Comment by aozarov** [comment]
The updates for `gcloud-java` to support `v1beta3` are ready and waiting to be merged in the [update-datastore](https://github.com/GoogleCloudPlatform/gcloud-java/tree/update-datastore) branch.

The merge will happen shortly after `v1beta3` is released (which is expected shortly but not in my control).

I do wonder if you are looking for anything specific to `v1beta3` which stops you from using the current client (based on `v1beta2`)?

**Comment by faizalkassamalisc** [comment]
@aozarov we are looking for API compatibility with the AppEngine Datastore API to ease moving code from GAE to GCE.  We are also looking for performance improvements since the current implementation is not usable at scale.

**Comment by aozarov** [comment]
Ok, I would say that from `gcloud-java` perspective the changes between `v1beta2` and `v1beta3` are not huge (so migration should not be too bad) however I get your point about performance. Indeed `v1beta3` should have an a noticeable improved performance.

**Comment by chrisbianca** [comment]
Now that v1beta3 is available, does that mean that the App Engine Java client library (and Objectify) should now work from Google Compute Engine?

**Comment by rickgittest** [comment]
@aozarov I really appreciate your earlier responses, but now I have the same question as chrisbianca. Hoping you or someone can clarify whether the app engine Java client API and Objectify work with the current version of Cloud Datastore. Also, has performance been improved to or near the level of app engine? Thanks in advance!

**Comment by rickgittest** [comment]
I seem to have found my own answer regarding Objectify support by Cloud Datastore. This page says it is now supported: v1 - https://cloud.google.com/datastore/docs/reference/libraries#client-libraries-usage-java

What about performance? Earlier posters said performance was a problem. Thanks.

**Comment by eddavisson** [comment]
The App Engine Java client and Objectify do not currently support the Cloud Datastore API.

**Comment by rickgittest** [comment]
@eddavisson Thanks. How unfortunate, however, it appears there is the intention to fix this in the future. From https://github.com/objectify/objectify/wiki/FrequentlyAskedQuestions#can-i-use-objectify-from-a-gae-flexible-runtime: 

> Can I use Objectify from a GAE Flexible Runtime?
> 
> Sort of. A little background:
> 
> For most of the history of GAE there were only Standard Runtimes. These launch one JVM per instance and connect to GAE services through a special interface called an ApiProxy. Objectify uses this ApiProxy.
> 
> Google is slowly building out REST-based interfaces to the GAE services. These perform much better when called from the Flexible Runtimes. However, the REST interface to the datastore differs significantly from the ApiProxy interface and therefore is not compatible with Objectify.
> 
> If you want to use Objectify from a Flexible Runtime, you must use the API compatibility layer that Google provides. Performance will be inferior to calling the datastore REST API or using Objectify on the Standard Runtime, but it will work. Test behavior to see if it satisfies your use case.
> 
> In the long run, Objectify will migrate to the new REST API and be usable from both the standard and flexible runtimes. However, the time for this is "not yet" - only a limited set of the GAE services are currently available via REST. Until it is possible to run a datastore transaction that enqueues a task via the REST API, the traditional ApiProxy is preferable for most applications.
> 
> >

**Comment by elharo** [comment]
Objectify RFEs can be filed against Objectify
