### ISSUE TITLE
Support the IN, OR, != operators in queries

### ISSUE THREAD

**Issue by eddavisson** [GoogleCloudPlatform/google-cloud-datastore#36]

**Comment by jamespedwards42** [comment]
Are there any plans for this feature, and if so, will it be implemented server side? 

I'm currently dependent on these features using the AppEngine RemoteAPI.  However, I recently discovered that the RemoteAPI has an undocumented query offset limit of 1000.  So I am trying to decide if I should hold out and use this library once it supports this or go ahead and implement a custom AppEngine servlet to proxy requests.

**Comment by eddavisson** [comment]
We would eventually like to support this server-side, but we don't have a timeline to share on that.

We're also working on porting [ndb](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/2) and the [App Engine Java client library](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/34) to work on top of Cloud Datastore. These libraries both support IN and OR by issuing multiple parallel queries from the client.

**Comment by Queatz** [comment]
Lemme know if there's any way I can help speed up the process.

**Comment by ajagnanan** [comment]
Will Not Equals be supported too?

**Comment by unitydynamics** [comment]
Various requests for "OR" have been around for quite some time.  From many people in many different issue names.  Is there a roadmap?  Programmers will move towards light.  Hopefully that's not AWS.

**Comment by bryanerayner** [comment]
I am also looking for a roadmap here.

**Comment by afeezaziz** [comment]
Hi, 

Is this something that GCP is looking into? OR is something quite important and I agree with @unitydynamics , hopefully the light is not AWS.

**Comment by dgadelha** [comment]
It has been almost 4 years...

**Comment by Bobchev** [comment]
Come on, guys ...

**Comment by teamrehab** [comment]
If you aren't going to actually do this, just close this issue. It's been 4ish years.

**Comment by laocoi** [comment]
5 years, I'm looking for that. Any update, please?

**Comment by elharo** [comment]
This is an RFE for the server side team, not the client.
