### ISSUE TITLE
null values not supported in JSON API

### ISSUE THREAD

**Issue by eddavisson** [GoogleCloudPlatform/google-cloud-datastore#41]
The following request:

```
{
 "mode": "NON_TRANSACTIONAL",
 "mutation": {
  "insertAutoId": [
   {
    "key": {
     "path": [
      {
       "kind": "test"
      }
     ]
    },
    "properties": {
     "propertyName": {
     }
    }
   }
  ]
 }
}
```

results in this response:

```
400 Bad Request
  
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "INVALID_ARGUMENT",
    "message": "Property \"propertyName\" has no value.",
   }
  ],
  "code": 400,
  "message": "Property \"propertyName\" has no value."
 }
}
```

Null values work correctly in the proto API but not JSON.

http://stackoverflow.com/questions/24141010/json-structure-to-insert-a-null-value-for-a-property-into-google-cloud-datastore/24174662

**Comment by afri** [comment]
FWIW, in a listValue the API tolerates null values, but (incorrectly) ignores them.
The request

    { mutation: { upsert: [
       {
          key: key,
          properties: {
            test: { listValue: [ {}, {stringValue: 'foo'}, {}, {stringValue: 'bar'} ] }
          }
       }]}
    }

succeeds, but then yields the following on a subsequent lookup:

    {
      ...
      properties: { 
        test: {
          listValue: [
            { stringValue: 'foo' },
            { stringValue: 'bar' }
          ]
        }
      }
    }

The null values have vanished.

**Comment by eddavisson** [comment]
The v1beta3 API adds an explicit null value type.
