### ISSUE TITLE
Migrate Node samples to gcloud

### ISSUE THREAD

**Issue by rakyll** [GoogleCloudPlatform/google-cloud-datastore#43]
We've just released a pre-stable [Datastore client] with user friendly interfaces as a part of gcloud npm module. Additionally, [googleapis] (the current client Node samples are using) is going to make a major release that will deprecate the current discovery model. We need to migrate to existing samples to gcloud.

[Datastore client]: https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-datastore
[googleapis]: https://github.com/google/google-api-nodejs-client

**Comment by broady** [comment]
+1, definitely should be linking to `gcloud-*` from the README to point people to the other libraries.

Mention that these libraries are low-level.

**Comment by eddavisson** [comment]
Cloud Datastore now has a [clients landing page](https://cloud.google.com/datastore/docs/client-libraries). The README in this project has been updated to point to that page and to make it very clear that these are low-level clients.
