### ISSUE TITLE
Long integer values not supported in the Python API's set_value / set_property / add_property helpers

### ISSUE THREAD

**Issue by cainau** [GoogleCloudPlatform/google-cloud-datastore#49]
Using long values with the set & add helper functions in the Python API results in an error like:
`TypeError: value type: 1015221965056L not supported`

The proto and Java API's support 64 bit integers, and long values up to 64 bit integer size work in Python if you set them directly, just not when using the helper functions.

**Comment by eddavisson** [comment]
The current version of set_value() in helper.py accepts longs.
