### ISSUE TITLE
High latency

### ISSUE THREAD

**Issue by sudhirj** [GoogleCloudPlatform/google-cloud-datastore#5]
[b/8334662](http://b/8334662)

I'm consistently seeing hight latency numbers when using the GCD - about 1.5 seconds on average for queries (10 items or less) and single item writes ( < 1kb). 

My ping time to the API endpoint is about 50ms, so discounting a 100ms round trip, that still leaves more than a second to GCD latency. This simply won't work for a server environment, certainly not one that scales. This is very surprising because I was expecting latencies much closer to GAE: https://code.google.com/status/appengine/detail/hr-datastore/2013/06/05#ae-trust-detail-hr-datastore-query-latency

Can we get a dashboard like the GAE HR Datastore status board? Possibly measuring latencies from Google Compute Engine instances and a few different AWS Regions?

**Comment by peterrham** [comment]
I'm measuring the latency between google cloud compute engine and google datastore. 

I'm performing a simple lookup() using the python client library.

The google performance dashboard says that my requests are consuming aroud 18 milliseconds. I assume that this is a server side metric and not a round trip metric.

Can someone refer me to the service level agreements behind the minimum round trip response times I should expect *currently* between google compute engine and google datastore?

For a trivial lookup, i'm experiencing around 60 milliseconds. I would expect around 20 milliseconds. 

Here's the code, not that some of these files are not strictly correlated. Each is intended to be indicative on its own. If someone can show me some code with better latencies, then that would be great.

https://github.com/peterrham/projects/blob/master/google_cloud/read.py

Here's an example output file:

https://github.com/peterrham/projects/blob/master/google_cloud/read.out

In this example, I'm getting 77 milliseconds. I'm not trying to be statistically significant here, I'm just looking for some indicative guidance.

Data store latency here is under 15 milliseconds:
http://code.google.com/status/appengine/detail/datastore/2015/02/02#ae-trust-detail-datastore-get-latency

I also have a sample tcpdump ascii text out put file:

https://github.com/peterrham/projects/blob/master/google_cloud/40ms.txt

using this command line: (the time stamps are the delta values *in between* the packet events)

/usr/sbin/tcpdump -r tcpdump.out -nnq -ttt > 40ms.txt

For example, the TCP initial SYN is acked in 1 millisecond, so network latency does not seem to be a problem.

However, the ack from the lookup() request is over 40 milliseconds after the request.

Server side latency from the app engine logs is 9 milliseconds:

2015-02-02 16:15:55.753 /datastore/v1beta2/Lookup 200 9ms 0kb module=default version=ah-builtin-datastoreservice
10.64.21.5 - - [02/Feb/2015:16:15:55 -0800] "POST /datastore/v1beta2/Lookup HTTP/1.1" 200 136 - - "ah-builtin-datastoreservice-dot-glowing-thunder-842.appspot.com" ms=10 cpu_ms=18 cpm_usd=0.000015 app_engine_release=1.9.17 instance=00c61b117c76349d57bd7ae2e3c635edd5c994da

any ideas? Are their any buffering configurations to setting to get the minimum latency?

**Comment by peterrham** [comment]
Looks like the 40ms is related to Nagle's algorithm, although I do not think that it accounts for the delayed response which is over 40ms, but i'm not sure.

http://neophob.com/2013/09/rpc-calls-and-mysterious-40ms-delay/

**Comment by gcjc** [comment]
Hi - we are doing some app and backend testing (prior to lunch) and are seeing this exact problem (looking at the ah-builtin-datastoreservice) we see times form 10-20ms to 2000ms. Do you have any timescale on a fix (or when you will apply any such fix already made to the current Beta channel)? Else we'll just migrate to Dynamo. Thanks.

**Comment by cerdmann** [comment]
I second the motion to move to Dynamo.

**Comment by andrewferk** [comment]
I am also disappointed with the performance I'm seeing from GCD. A couple patterns I've noticed: 1) the first request from a new datastore connection is always slow, and 2) batch mutations (even a batch of 100 entities) is painfully slow.

**Comment by obeleh** [comment]
In my experience it is better than it was when this issue was opened. I used to see a lot more response times between 500ms and 1000ms. Most of my requests are between 200ms and 500ms. Perhaps I've segmented my data better?

**Comment by hbizira** [comment]
@cerdmann @gcjc I would advise against moving to dynamodb if you're concerned about keeping costs as low as possible. I did an evaluation after hitting this issue and in my opinion dynamodb has one major drawback. You have to provision your read/write capacity ahead of time. This makes it difficult to adjust to a sudden spike in traffic while keeping costs down. There are some auto scaling libraries that attempt to help with this but their adjustment time is not very fast and dynamo currently limits you to scaling back down only a few times a day.  

I'm really hoping this issue gets fixed soon as there's a huge node.js community that could really take advantage of GCD.

**Comment by gcjc** [comment]
@obeleh it is hard to predict when there will be problems (and it seems to be any operation).

We will likely knock up some longer running tests internally to see if we can spot any patterns. However, we just ran a very short test and it seems to have improved, most requests between 150-220ms. Anyone else seen any improvement, just wondering if any changes in the app engine front end have been made? 

@hbizira we really do want to use GCD, moving to dynamo will be the last resort.

**Comment by cerdmann** [comment]
@hbizira, thanks for the advice. I'm in the same boat as @gcjc in that we really want to use GCD, but looking into other options as the latency is killing us.

**Comment by jonface** [comment]
Just started using gcloud via nodejs and it's a bit disappointing. Getting from 200ms - 500ms approx latency. This is running on RH OpenShift (really AWS) in the US and EU. Tried my home connection too, all roughly the same.

I hope I'm doing something wrong :/

**Comment by peterrham** [comment]
I got better results than that, but still not great. What do you mean
"AWS"? My timings were from a google compute host to google cloud datastore.

By the way, I'm trying out google "bigtable" which is in Beta. It promises
a great SLA sub 10 ms for 99 percentile I think. I have tried it out, but
have not measured the latency, but I believe it!

**Comment by jonface** [comment]
I was referring to Amazon Web Services EC2 which is the underlying infrastructure of OpenShift. Isn't BigTable more expensive and overkill? 

I'll check my timings with wireshark. Also my datastore is empty, so it's not like it's got millions of items in it.

**Comment by jonface** [comment]
OK, it's hard to tell exactly how long it's taking via wireshark due to the TLS but you can kind of guess. 

TLS connection SYN to FIN - total 460ms
	- TLS Application data at 126ms
	- TLS Application data at 201ms
	- TLS Application data at 399ms
	- TLS Application data at 400ms
	- TLS Application data at 455ms

What is interesting is that for every query, a new connection is setup/destroyed. Is this correct? Am I doing something wrong? Would it not be better to keep some connection pool and reuse connections?

Thanks

**Comment by jonface** [comment]
I realise I'm being impatient but what's the plan for this? Is this just a nodejs lib problem?

**Comment by dhermes** [comment]
@pcostell Will this be addressed with `v1beta3`?

**Comment by pcostell** [comment]
That is the goal, but we are still working on benchmarking v1beta3.

**Comment by InfiniteRandomVariable** [comment]
@pcostell I am seriously considering this service. Please post an update about this issue since it has been a while. Thanks for the great work.

**Comment by pcostell** [comment]
We are seeing much better latency numbers with v1beta3. v1beta3 has been a complete rewrite in our infrastructure and as such we are being very cautious about rolling it out. We hope to have it ready early this year.

**Comment by peterrham** [comment]
Great!

**Comment by alexfernandez** [comment]
@pcostell What numbers are you seeing? Anything below 20 ms? That is the performance goal that we have, and it is easily achievable in DynamoDB. This issue is a dealbreaker for us for moving to Google Cloud right now.

**Comment by leonardaustin** [comment]
I thought I would share some instrumentation as I found this issue and have been following it with interest. Below is 95th percentile and mean (in milli-seconds) for PUT requests moving from v1beta2 to v1beta3. Both show an increase of ~10x (~25ms & ~10ms) - good work guys! It would also be nice to get it out of beta endpoints for us to use in production. One thing worth mentioning is that the v1beta3 seems to be missing the transaction endpoint.

95th
![screen shot 2016-02-15 at 18 22 57](https://cloud.githubusercontent.com/assets/1532733/13056999/2eb062f6-d411-11e5-8796-6c499294d3bb.png)

Mean
![screen shot 2016-02-15 at 18 25 17](https://cloud.githubusercontent.com/assets/1532733/13057093/b9c84ff2-d411-11e5-8285-af7ca300707f.png)

**Comment by eddavisson** [comment]
Hi @leonardaustin, can you share details about what service(s) you're using? We haven't actually launched v1beta3 yet, so I'm wondering if we're talking about two different things.

**Comment by leonardaustin** [comment]
@eddavisson Sure, I forked https://github.com/GoogleCloudPlatform/gcloud-golang and changed the url from v1beta2 to v1beta3.

**Comment by dhermes** [comment]
`gcloud-python` has "already" made the switch (in a branch)
- [`v1beta2`][1] in main branch
- [`v1beta3`][3] in custom branch

All features from `v1beta3` are present, though the URIs are different.

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/
[2]: https://github.com/GoogleCloudPlatform/gcloud-python/tree/datastore-v1beta3

**Comment by obeleh** [comment]
Is there a list of changes I should see or can I just change the url and I'm set?

**Comment by eddavisson** [comment]
The v1beta3 API is not yet available to customers. We will be sure to post announcement here when it is.

**Comment by obeleh** [comment]
If possible I would like to sign up for the public beta of the beta?

**Comment by faizalkassamalisc** [comment]
@pcostell, is v1beta3 still on track to "be released this quarter" as per  https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/34? :)

![image](http://ocramius.github.io/presentations/doctrine-orm-and-zend-framework-2/assets/img/waiting-meme.png)

**Comment by dmcgrath** [comment]
@faizalkassamalisc, we're busy reticulating splines and hopefully will have an update for you soon. Thanks for your patience!

@obeleh, the beta will be public and just requires you using the appropriate API clients. There will be no other sign-up beyond the normal project creation you do currently.

**Comment by pcostell** [comment]
https://cloudplatform.googleblog.com/2016/04/Google-Cloud-Datastore-gets-faster-cross-platform-API.html

**Comment by alexfernandez** [comment]
Is there a more technical page with latencies expressed as milliseconds? Thanks!

**Comment by dmcgrath** [comment]
We don't have a page with latency numbers since it's a moving target as we continually improve the platform as well as depending upon both the location your Cloud Datastore was set up for as well as from where you are accessing it.

Keep in mind you cannot compare DynamoDB with Cloud Datastore directly as we're a functionally different service and in most cases are serving customers in a Multi-Regional instance vs merely Regional.

**Comment by rajeshshetty** [comment]
Why the first request from a new datastore connection is always slow? 
Is there a way to fix this.

**Comment by StdInOut** [comment]
Hello Guys, It is probably the wrong place for ask this question but I didn't find any better place.

Could datastore using local disks play the same role of redis in session cache? Everything would be much easier and cheaper to our company.

**Comment by manwithsteelnerves** [comment]
Is this ever solved? Any one share how much are the latencies we can expect now on data store(Firestore with datastore mode vs native mode)?
