### ISSUE TITLE
New Code For Node.js Sample Needed

### ISSUE THREAD

**Issue by anywhichway** [GoogleCloudPlatform/google-cloud-datastore#55]
The existing code for the node.js example is both complex and broken. It won't work with the most recent googleapis version. Below is code that is simple and will connect and authenticate. Querying is another issue, see open bug on this:

'var util = require('util');
var google = require("googleapis");
var SCOPES = ['https://www.googleapis.com/auth/userinfo.email',
              'https://www.googleapis.com/auth/datastore'];
var datasetId = "<your-dataset-id>";
credentials = new google.auth.JWT(
        process.env['DATASTORE_SERVICE_ACCOUNT'],
        process.env['DATASTORE_PRIVATE_KEY_FILE'],
        null,
        SCOPES);
credentials.authorize((function(jwtErr) {
  if (jwtErr) {
    errors = {'jwt auth error':jwtErr};
    console.log(errors);
    return;
  }
  var cloudstore = google.datastore('v1beta2').datasets;

<your code and queries here using the cloudstore variable>'

**Comment by eddavisson** [comment]
Closing since we've removed the Node.js sample from the repo.

Check out [gcloud-node](https://github.com/GoogleCloudPlatform/gcloud-node#google-cloud-datastore) as an option for accessing Google Cloud Datastore from Node.
