### ISSUE TITLE
What does this repo do? What should it do?

### ISSUE THREAD

**Issue by ryanseys** [GoogleCloudPlatform/google-cloud-datastore#57]
There's been a bunch of discussion (recently mostly me just rambling to myself) around what to do with the stale nodejs samples in this repo now that `googleapis` and `gcloud` have both been updated/created. I've been wondering what the point of this repo is nowadays... Three paragraphs into the README it says "This repository contains the source code of samples and developer resources related to Google Cloud Datastore". I think if developers want to learn about Datastore in general, the https://cloud.google.com/datastore website is best for that. Samples should be found in their respective api client repos in an `examples` folder or available in their own repo altogether e.g. like `gcloud-node-todos`. 

So can someone shine some light on what this repo is meant to accomplish that is not already being accomplished in other repos or websites? This repo hasn't been getting much love recently and I'm curious if it's really useful anymore.

**Comment by eddavisson** [comment]
I've updated the README file to make it clear that these are low-level clients and to steer developers towards the https://cloud.google.com/datastore website.
