### ISSUE TITLE
Dataset ID aliases don't behave consistently.

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-datastore#59]
Using the "human-readable" version `foo` of the prefixed ID `s~foo` (or `e~foo`) is allowed in a URI but not in a request payload (and will never be returned in a response since `foo` gets mapped to `s~foo` in the response).

This inconsistency can catch user's off-guard and requires custom behavior in `to_protobuf()`-type methods which essentially always ignore the `dataset_id` on a `PartitionId` message and only use the dataset ID in the URI.

/cc @silvolu @tseaver

----------------------------

Some examples

1.  Sending a query to

    ```
    https://www.googleapis.com/datastore/v1beta2/datasets/foo/runQuery
    ```

    which has `RunQueryRequest.partition_id.dataset_id == 'foo'` in the payload results in

    ```
    app s~foo cannot access app foo&#39;s data
    ```

1.  Sending a mutation (or a lookup) to one of

    ```
    https://www.googleapis.com/datastore/v1beta2/datasets/foo/allocateIds
    https://www.googleapis.com/datastore/v1beta2/datasets/foo/commit
    https://www.googleapis.com/datastore/v1beta2/datasets/foo/lookup
    ```

    which has `Key.partition_id.dataset_id == 'foo'` (either directly in a key
    or in an `Entity`) in the payload results in

    ```
    app s~foo cannot access app foo&#39;s data
    ```

1.  Sending a filtered or ancestor query which does not have
    `RunQueryRequest.partition_id.dataset_id` set in the payload but does have
    the dataset ID set in either the ancestor key

    ```
    The query app is &#39;foo&#39; but ancestor.key app is &#39;foo&#39;.
    ```

    or in the `__key__` filter

    ```
    __key__ filter app is foo but query app is s~foo
    ```

**Comment by dhermes** [comment]
@eddavisson @pcostell Do you have an idea of when this might land?

**Comment by dhermes** [comment]
@pcostell will this be addressed in `v1beta3`?

**Comment by eddavisson** [comment]
Yes.

**Comment by dhermes** [comment]
w00t!

**Comment by pcostell** [comment]
Per https://cloud.google.com/datastore/release-notes, in `v1beta3` it is always `project_id` and never includes the prefix ("s~" and friends).
