### ISSUE TITLE
unknown transaction handle

### ISSUE THREAD

**Issue by enzomd** [GoogleCloudPlatform/google-cloud-datastore#61]
https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/v1beta2-rev1-2.1.1/ruby/demos/trivial/adams.rb#L62

puts resp.inspect 

Gives me:
```
{\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"INVALID_ARGUMENT\",\n    \"message\": \"unknown transaction handle\"\n   }\n  ],\n  \"code\": 400,\n  \"message\": \"unknown transaction handle\"\n }
```
ruby 2.1.2p95 (2014-05-08) [x86_64-linux-gnu]
google-api-client (0.8.2)

Is there something im missing?

**Comment by eddavisson** [comment]
Closing this as obsolete, but please re-open if you're still seeing this issue.

Check out [gcloud-ruby](https://github.com/GoogleCloudPlatform/gcloud-ruby#datastore) as an option for accessing Google Cloud Datastore from Ruby.
