### ISSUE TITLE
Support for Datastore Statistics

### ISSUE THREAD

**Issue by andrewferk** [GoogleCloudPlatform/google-cloud-datastore#62]
Is there any support for [Datastore Statistics](https://cloud.google.com/appengine/docs/java/datastore/stats) or any plans to support it? It seems this is a limitation of the JSON and Protobuf APIs.

Thanks,
Andrew

**Comment by eddavisson** [comment]
This should work today. For instance, you can get an entity containing the overall stats by executing the GQL query:

 `SELECT * FROM __Stat_Total__`

**Comment by dhermes** [comment]
@eddavisson Was this resolved somehow?

**Comment by eddavisson** [comment]
@dhermes AFAIK, this has been working all along. The datastore statistics feature consists of a number of specially-named entities -- they can be read through the Cloud Datastore API the same as any other entity.

**Comment by dhermes** [comment]
Yeah that's the way I understand it as well.

I was interpreting this issue as a request for a standalone doc of what these entities are. The description in
https://cloud.google.com/appengine/docs/java/datastore/stats
is pretty comprehensive but the doc itself is Java specific (so it may scare away users that don't read down far enough to see the general info).

**Comment by eddavisson** [comment]
Ah, that page is here:
https://cloud.google.com/datastore/docs/concepts/stats

**Comment by dhermes** [comment]
w00t! Thanks
