### ISSUE TITLE
gcloud.storage.get_bucket throws AttributeError 'api_rquest

### ISSUE THREAD

**Issue by charlesbclifford** [GoogleCloudPlatform/google-cloud-datastore#66]
I'm testing an installation of Google SDK on Fedora 22 (a fresh new installation). And when I test the installation by running this Python script:

$ python
Python 2.7.8 (default, Apr 15 2015, 09:26:43) 
[GCC 4.9.2 20150212 (Red Hat 4.9.2-6)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gcloud
>>> from gcloud import storage
>>> storage.set_default_bucket("ccb_ci_acct")
>>> storage.set_default_project('applied-algebra-93003')
>>> storage_conn = storage.get_connection()
>>> 
>>> storage.set_default_connection(storage_conn)
>>> bucket=storage.get_bucket("ccb_ci_acct","applied-algebra-93003")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/gcloud/storage/api.py", line 165, in get_bucket
    bucket.reload()
  File "/usr/lib/python2.7/site-packages/gcloud/storage/_helpers.py", line 57, in reload
    self._properties = self.connection.api_request(
AttributeError: 'str' object has no attribute 'api_request'
>>> 

The Python shell returns the above AttributeError message. My guess is that the installed host is missing either some Python module, or, in the above code, a mandatory configuration parameter is not being set.

Any suggestions to fix this problem are appreciated.

**Comment by eddavisson** [comment]
This looks like an issue with [gcloud-python](https://github.com/GoogleCloudPlatform/gcloud-python). Can you file the issue there instead?
