### ISSUE TITLE
GCD Local Server gcd-v1beta2-rev1-3.0.0 binary matches 2.1.1

### ISSUE THREAD

**Issue by risaacson** [GoogleCloudPlatform/google-cloud-datastore#72]
I am not sure if this is a good place to point this over to get some eyes on it but it is worth a try.

```bash
wget http://storage.googleapis.com/gcd/tools/gcd-v1beta2-rev1-3.0.0.zip
```
when uncompressed expands as gcd-v1beta2-rev1-2.1.1 and seems identical to

```bash
wget http://storage.googleapis.com/gcd/tools/gcd-v1beta2-rev1-2.1.1.zip
```

Is this by design or mistake?

**Comment by eddavisson** [comment]
Thanks for pointing this out. There were no changes in the new version of the tool, but the version number in the expanded directory name should have been updated. I'll work on getting this fixed.

**Comment by eddavisson** [comment]
Updated the file.
