### ISSUE TITLE
New release with LocalDevelopmentDatastore fix

### ISSUE THREAD

**Issue by AlexanderLitus** [GoogleCloudPlatform/google-cloud-datastore#81]
Hello,

When are you going to make a new release with the [LocalDevelopmentDatastore fix](https://github.com/GoogleCloudPlatform/google-cloud-datastore/commit/a077c5b4d6fa2826fd6c376b692686894b719fd9)?

**Comment by eddavisson** [comment]
This is part of v1beta2-rev1-3.0.4.
