### ISSUE TITLE
upgrading oauth2client dep?

### ISSUE THREAD

**Issue by ericgj** [GoogleCloudPlatform/google-cloud-datastore#84]
The current version of oauth2client is 1.5.2, this library uses 1.2, released years ago. Is there any plan to upgrade?  I am running into conflicts with other Google libraries that use the latest oauth2client, e.g. `google-api-python-client`.

**Comment by eddavisson** [comment]
v1beta2-rev1-3.0.4 relaxes the version restriction somewhat -- it now requires oauth2client>=1.2,<2. Does that resolve the conflict?

**Comment by ericgj** [comment]
Thanks. I assume you mean 3.0.4b1 ?  pip didn't find a v1beta2-rev1-3.0.4 .  Anyway, that seems to work.

**Comment by eddavisson** [comment]
Sorry, that's correct: 3.0.4b1.

**Comment by ericgj** [comment]
thanks again!
