### ISSUE TITLE
missing support for valid datastore value types

### ISSUE THREAD

**Issue by faizalkassamalisc** [GoogleCloudPlatform/google-cloud-datastore#90]
There are a number of data types on https://cloud.google.com/appengine/docs/java/datastore/entities#Java_Properties_and_value_types that I don't see support for when building Value objects through this API: https://cloud.google.com/datastore/docs/apis/javadoc/com/google/api/services/datastore/DatastoreV1.Value.Builder

For example, com.google.appengine.api.users.User, com.google.appengine.api.datastore.PostalAddress, etc.

**Comment by pcostell** [comment]
These types are not supported natively in the new Datastore API and instead we rely on clients to implement these as necessary on a per-application basis. The rational here is that the Datastore API should be as simple as possible and push application logic up the stack. For example with the `PostalAddress` type it may make sense for the application to validate/normalize the address (for example by using the Google Maps API), then storing it as a String in Datastore. Importantly, Datastore doesn't/shouldn't know what that string represents.

For these types which were stored using the App Engine Datastore libraries, they are accessible as more generic types. For example, storing a User property in App Engine would look like an `entity_value` property in the Cloud Datastore API with `email`, `auth_domain`, and `user_id` properties.

The `PostalAddress` type is stored as a `string_value` (which is how it is actually stored in Datastore).
