### ISSUE TITLE
gcloud._helpers._compute_engine_id should return a str (Python 3)

### ISSUE THREAD

**Issue by flunderpero** [GoogleCloudPlatform/google-cloud-datastore#92]
I stumbled upon this while deploying my app for the first time on GKE/GCE.

I had to explicitly specify `project` when creating a client: `gcloud.datastore.Client(project="my-project")`, otherwise I just got an `gcloud.exceptions.ServiceUnavailable: 503 Backend Error`.

First I thought the problem would be that autodetecting the project-id didn't work, but `gcloud.datastore.Client(credentials=credentials, project=project)` returns my project-id, be it as `bytes` instead of `str`.

I quickly verified that using `bytes` as a project-id does not work, i.e. `gcloud.datastore.Client(project=b"my-project")` resulted in that neat `503 Backend Error`.

**Comment by pcostell** [comment]
Moved over to gcloud-python.
