### ISSUE TITLE
Cannot ENABLE any API when there is a pending request to DISABLE any API

### ISSUE THREAD

**Issue by Queatz** [GoogleCloudPlatform/google-cloud-datastore#97]
I've been trying to use the Cloud Datastore API with Java, however it's been throwing this error:

`com.google.gcloud.datastore.DatastoreException: The Cloud Datastore API is not enabled for the project <project-id>
`

However, when I try to enable it in the Google Cloud Console API Manager (https://console.cloud.google.com/apis/api/datastore.googleapis.com/overview), it shows another error:

![screenshot from 2016-04-03 16-44-09](https://cloud.githubusercontent.com/assets/540620/14235737/5d7c7ea6-f9bb-11e5-89e2-bf0b704fd259.png)

This is persistent and happens every time, and I don't have any pending requests to disable any APIs.

The end result?  Absolutely no way to use the Cloud Datastore API!!

**Comment by pcostell** [comment]
Thanks for the report, we've escalated to the team that handles service management, I'll let you know when we get more information.

**Comment by Queatz** [comment]
Just tried again this evening and the great news is that it's been resolved.  Thanks for looking into it.

**Comment by eddavisson** [comment]
@Queatz Would you be willing to share the project ID you were using when you saw this error? It'd help us ensure this issue doesn't recur. You can email me at eddavisson@google.com. Thanks!

**Comment by Queatz** [comment]
@eddavisson yup - sent it your way.
